# Generated by Django 4.2.8 on 2023-12-12 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("-created_date",),
                "verbose_name": "Users Account",
                "verbose_name_plural": "Users Account",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="account_key",
            field=models.CharField(
                help_text="The stores the account hash key",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Account Key",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp when the record was created. The date and time \n            are displayed in the Timezone from where request is made. \n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC",
                verbose_name="Created",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modified_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the record was modified. The date and \n            time are displayed in the Timezone from where request \n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ",
                null=True,
                verbose_name="Updated",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="The email address of the customer.",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
    ]
